---
deployment:
  tasks:
    - export DEPLOYPATH=/home4/washpres/
    - /bin/cp -r * $DEPLOYPATH/public_html/bookings.washpress.com.au #copy all from root
    # - /bin/cp -r ./public/* $DEPLOYPATH/public_html/dashboard.codignore.com
    # - /bin/cp ./public/js/*.js $DEPLOYPATH/public_html/welikework.codignore.com/js
    # - /bin/cp ./public/css/*.css $DEPLOYPATH/public_html/welikework.codignore.com/css